// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: adoption/v1/flock.proto

package adoptionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlockService_Adopt_FullMethodName     = "/adoption.v1.FlockService/Adopt"
	FlockService_Heartbeat_FullMethodName = "/adoption.v1.FlockService/Heartbeat"
)

// FlockServiceClient is the client API for FlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlockServiceClient interface {
	// Controller calls this to adopt a node
	Adopt(ctx context.Context, in *AdoptRequest, opts ...grpc.CallOption) (*AdoptResponse, error)
	// Compute nodes call this to heartbeat/check-in
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type flockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlockServiceClient(cc grpc.ClientConnInterface) FlockServiceClient {
	return &flockServiceClient{cc}
}

func (c *flockServiceClient) Adopt(ctx context.Context, in *AdoptRequest, opts ...grpc.CallOption) (*AdoptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptResponse)
	err := c.cc.Invoke(ctx, FlockService_Adopt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flockServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, FlockService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlockServiceServer is the server API for FlockService service.
// All implementations must embed UnimplementedFlockServiceServer
// for forward compatibility.
type FlockServiceServer interface {
	// Controller calls this to adopt a node
	Adopt(context.Context, *AdoptRequest) (*AdoptResponse, error)
	// Compute nodes call this to heartbeat/check-in
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedFlockServiceServer()
}

// UnimplementedFlockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlockServiceServer struct{}

func (UnimplementedFlockServiceServer) Adopt(context.Context, *AdoptRequest) (*AdoptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Adopt not implemented")
}
func (UnimplementedFlockServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedFlockServiceServer) mustEmbedUnimplementedFlockServiceServer() {}
func (UnimplementedFlockServiceServer) testEmbeddedByValue()                      {}

// UnsafeFlockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlockServiceServer will
// result in compilation errors.
type UnsafeFlockServiceServer interface {
	mustEmbedUnimplementedFlockServiceServer()
}

func RegisterFlockServiceServer(s grpc.ServiceRegistrar, srv FlockServiceServer) {
	// If the following call panics, it indicates UnimplementedFlockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlockService_ServiceDesc, srv)
}

func _FlockService_Adopt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlockServiceServer).Adopt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlockService_Adopt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlockServiceServer).Adopt(ctx, req.(*AdoptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlockService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlockServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlockService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlockServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlockService_ServiceDesc is the grpc.ServiceDesc for FlockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adoption.v1.FlockService",
	HandlerType: (*FlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Adopt",
			Handler:    _FlockService_Adopt_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _FlockService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adoption/v1/flock.proto",
}
