// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: adoption/v1/flock.proto

package adoptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdoptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterToken  string                 `protobuf:"bytes,1,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	ControllerIp  string                 `protobuf:"bytes,2,opt,name=controller_ip,json=controllerIp,proto3" json:"controller_ip,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "server" or "agent"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptRequest) Reset() {
	*x = AdoptRequest{}
	mi := &file_adoption_v1_flock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptRequest) ProtoMessage() {}

func (x *AdoptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_v1_flock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptRequest.ProtoReflect.Descriptor instead.
func (*AdoptRequest) Descriptor() ([]byte, []int) {
	return file_adoption_v1_flock_proto_rawDescGZIP(), []int{0}
}

func (x *AdoptRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *AdoptRequest) GetControllerIp() string {
	if x != nil {
		return x.ControllerIp
	}
	return ""
}

func (x *AdoptRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AdoptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptResponse) Reset() {
	*x = AdoptResponse{}
	mi := &file_adoption_v1_flock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptResponse) ProtoMessage() {}

func (x *AdoptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_v1_flock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptResponse.ProtoReflect.Descriptor instead.
func (*AdoptResponse) Descriptor() ([]byte, []int) {
	return file_adoption_v1_flock_proto_rawDescGZIP(), []int{1}
}

func (x *AdoptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdoptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_adoption_v1_flock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_v1_flock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_adoption_v1_flock_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reconfigure   bool                   `protobuf:"varint,1,opt,name=reconfigure,proto3" json:"reconfigure,omitempty"` // If true, node should revert to pending state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_adoption_v1_flock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_v1_flock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_adoption_v1_flock_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetReconfigure() bool {
	if x != nil {
		return x.Reconfigure
	}
	return false
}

var File_adoption_v1_flock_proto protoreflect.FileDescriptor

const file_adoption_v1_flock_proto_rawDesc = "" +
	"\n" +
	"\x17adoption/v1/flock.proto\x12\vadoption.v1\"l\n" +
	"\fAdoptRequest\x12#\n" +
	"\rcluster_token\x18\x01 \x01(\tR\fclusterToken\x12#\n" +
	"\rcontroller_ip\x18\x02 \x01(\tR\fcontrollerIp\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"C\n" +
	"\rAdoptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x11HeartbeatResponse\x12 \n" +
	"\vreconfigure\x18\x01 \x01(\bR\vreconfigure2\x9a\x01\n" +
	"\fFlockService\x12>\n" +
	"\x05Adopt\x12\x19.adoption.v1.AdoptRequest\x1a\x1a.adoption.v1.AdoptResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.adoption.v1.HeartbeatRequest\x1a\x1e.adoption.v1.HeartbeatResponseB\xae\x01\n" +
	"\x0fcom.adoption.v1B\n" +
	"FlockProtoP\x01ZBgithub.com/lunarhue/compute-flock/pkg/proto/adoption/v1;adoptionv1\xa2\x02\x03AXX\xaa\x02\vAdoption.V1\xca\x02\vAdoption\\V1\xe2\x02\x17Adoption\\V1\\GPBMetadata\xea\x02\fAdoption::V1b\x06proto3"

var (
	file_adoption_v1_flock_proto_rawDescOnce sync.Once
	file_adoption_v1_flock_proto_rawDescData []byte
)

func file_adoption_v1_flock_proto_rawDescGZIP() []byte {
	file_adoption_v1_flock_proto_rawDescOnce.Do(func() {
		file_adoption_v1_flock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adoption_v1_flock_proto_rawDesc), len(file_adoption_v1_flock_proto_rawDesc)))
	})
	return file_adoption_v1_flock_proto_rawDescData
}

var file_adoption_v1_flock_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_adoption_v1_flock_proto_goTypes = []any{
	(*AdoptRequest)(nil),      // 0: adoption.v1.AdoptRequest
	(*AdoptResponse)(nil),     // 1: adoption.v1.AdoptResponse
	(*HeartbeatRequest)(nil),  // 2: adoption.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: adoption.v1.HeartbeatResponse
}
var file_adoption_v1_flock_proto_depIdxs = []int32{
	0, // 0: adoption.v1.FlockService.Adopt:input_type -> adoption.v1.AdoptRequest
	2, // 1: adoption.v1.FlockService.Heartbeat:input_type -> adoption.v1.HeartbeatRequest
	1, // 2: adoption.v1.FlockService.Adopt:output_type -> adoption.v1.AdoptResponse
	3, // 3: adoption.v1.FlockService.Heartbeat:output_type -> adoption.v1.HeartbeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adoption_v1_flock_proto_init() }
func file_adoption_v1_flock_proto_init() {
	if File_adoption_v1_flock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adoption_v1_flock_proto_rawDesc), len(file_adoption_v1_flock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adoption_v1_flock_proto_goTypes,
		DependencyIndexes: file_adoption_v1_flock_proto_depIdxs,
		MessageInfos:      file_adoption_v1_flock_proto_msgTypes,
	}.Build()
	File_adoption_v1_flock_proto = out.File
	file_adoption_v1_flock_proto_goTypes = nil
	file_adoption_v1_flock_proto_depIdxs = nil
}
